# Generated by Django 4.0.3 on 2022-06-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=256)),
                ('nama_kk', models.CharField(max_length=256)),
                ('alamat', models.CharField(max_length=512)),
                ('pekerjaan', models.CharField(max_length=128)),
                ('tanggal_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('no_telp', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
