# Generated by Django 4.1.5 on 2023-02-10 03:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=256, verbose_name='Nama Lengkap')),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin')),
                ('nama_kk', models.CharField(max_length=256, verbose_name='Nama Kepala Keluarga')),
                ('tempat_lahir', models.CharField(blank=True, max_length=32, verbose_name='Tempat Lahir')),
                ('tanggal_lahir', models.DateField(verbose_name='Tanggal Lahir')),
                ('nama_ayah_suami', models.CharField(blank=True, max_length=256, verbose_name='Nama Ayah / Suami')),
                ('alamat', models.CharField(max_length=512, verbose_name='Alamat')),
                ('alamat_rt', models.CharField(blank=True, max_length=5, verbose_name='RT')),
                ('alamat_rw', models.CharField(blank=True, max_length=5, verbose_name='RW')),
                ('alamat_kel_desa', models.CharField(blank=True, max_length=32, verbose_name='Kelurahan / Desa')),
                ('alamat_kecamatan', models.CharField(blank=True, max_length=32, verbose_name='Kecamatan')),
                ('alamat_kota_kab', models.CharField(blank=True, max_length=32, verbose_name='Kota / Kabupaten')),
                ('alamat_provinsi', models.CharField(blank=True, max_length=32, verbose_name='Provinsi')),
                ('alamat_kode_pos', models.CharField(blank=True, max_length=5, verbose_name='Kode Pos')),
                ('no_telp', models.CharField(blank=True, max_length=20, verbose_name='No. Telepon')),
                ('pekerjaan', models.CharField(max_length=128, verbose_name='Pekerjaan')),
                ('status_perkawinan', models.CharField(blank=True, choices=[('BL', 'Belum Menikah'), ('SD', 'Menikah'), ('JD', 'Janda / Duda'), ('', '-')], default='', max_length=2, verbose_name='Status Perkawinan')),
                ('agama', models.CharField(blank=True, choices=[('islam', 'Islam'), ('katolik', 'Katolik'), ('protestan', 'Protestan'), ('hindu', 'Hindu'), ('budha', 'Budha'), ('lainnya', 'Lainnya'), ('', '-')], default='', max_length=10, verbose_name='Agama')),
                ('cara_bayar', models.CharField(blank=True, choices=[('C', 'Tunai'), ('T', 'Transfer'), ('', '-')], default='', max_length=1, verbose_name='Cara Pembayaran')),
                ('tanggal', models.DateField(null=True, verbose_name='Tanggal')),
                ('promosi', models.BooleanField(null=True, verbose_name='Promosi')),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('waktu_diubah', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membuat_pasien', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
