# Generated by Django 4.1.7 on 2023-08-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekam_medis", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perjanjian",
            name="waktu_selesai",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
