# Generated by Django 4.0.3 on 2022-06-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekam_medis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasien',
            name='agama',
            field=models.CharField(blank=True, choices=[('islam', 'Islam'), ('katolik', 'Katolik'), ('protestan', 'Protestan'), ('hindu', 'Hindu'), ('budha', 'Budha'), ('lainnya', 'Lainnya'), ('', '-')], default='', max_length=10, verbose_name='Agama'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_kecamatan',
            field=models.CharField(blank=True, max_length=32, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_kel_desa',
            field=models.CharField(blank=True, max_length=32, verbose_name='Kelurahan / Desa'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_kode_pos',
            field=models.CharField(blank=True, max_length=5, verbose_name='Kode Pos'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_kota_kab',
            field=models.CharField(blank=True, max_length=32, verbose_name='Kota / Kabupaten'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_provinsi',
            field=models.CharField(blank=True, max_length=32, verbose_name='Provinsi'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_rt',
            field=models.CharField(blank=True, max_length=5, verbose_name='RT'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='alamat_rw',
            field=models.CharField(blank=True, max_length=5, verbose_name='RW'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='cara_bayar',
            field=models.CharField(blank=True, choices=[('C', 'Tunai'), ('T', 'Transfer'), ('', '-')], default='', max_length=1, verbose_name='Cara Pembayaran'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='nama_ayah_suami',
            field=models.CharField(blank=True, max_length=256, verbose_name='Nama Ayah / Suami'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='promosi',
            field=models.BooleanField(null=True, verbose_name='Promosi'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='status_perkawinan',
            field=models.CharField(blank=True, choices=[('BL', 'Belum Menikah'), ('SD', 'Menikah'), ('JD', 'Janda / Duda'), ('', '-')], default='', max_length=2, verbose_name='Status Perkawinan'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tanggal',
            field=models.DateField(null=True, verbose_name='Tanggal'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=32, verbose_name='Tempat Lahir'),
        ),
        migrations.AddField(
            model_name='pasien',
            name='waktu_diubah',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='alamat',
            field=models.CharField(max_length=512, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, verbose_name='Jenis Kelamin'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nama',
            field=models.CharField(max_length=256, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='nama_kk',
            field=models.CharField(max_length=256, verbose_name='Nama Kepala Keluarga'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='no_telp',
            field=models.CharField(blank=True, max_length=20, verbose_name='No. Telepon'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='pekerjaan',
            field=models.CharField(max_length=128, verbose_name='Pekerjaan'),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='tanggal_lahir',
            field=models.DateField(verbose_name='Tanggal Lahir'),
        ),
    ]
