# Generated by Django 4.1.7 on 2023-10-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rekam_medis", "0002_alter_perjanjian_waktu_selesai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perjanjian",
            name="waktu_selesai",
        ),
        migrations.AddField(
            model_name="perjanjian",
            name="catatan",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="perjanjian",
            name="estimasi_durasi",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="perjanjian",
            name="status",
            field=models.CharField(
                choices=[
                    ("menunggu", "Menunggu Konfirmasi"),
                    ("terjadwal", "Terjadwal"),
                    ("selesai", "Selesai"),
                ],
                default="menunggu",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="perjanjian",
            name="waktu_mulai",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
